project/models.py
from datetime import datetime
from project import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    products = db.relationship(
        "Product", backref="owner", cascade="all, delete-orphan", lazy="dynamic"
    )

    def __repr__(self):
        return "<User {}>".format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    url = db.Column(db.String())

    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def __repr__(self):
        return "<Product {}>".format(self.title)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

project/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length
from project.models import User


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember_me = BooleanField("Remember Me")
    submit = SubmitField("Sign In")


class RegistrationForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    password2 = PasswordField(
        "Repeat Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Register")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError("Please use a different username.")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError("Please use a different email address.")


class ProductForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    url = TextAreaField(
        "Poshmark Web URL", validators=[DataRequired(), Length(min=1, max=500)]
    )
    submit = SubmitField("Submit")

    def validate_url(self, url):
        if "poshmark.com" not in url.data:
            raise ValidationError("Please use a valid Poshmark URL.")

project/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


db = SQLAlchemy(session_options={"expire_on_commit": False})
migrate = Migrate()
login = LoginManager()
login.login_view = "login"


def create_app(script_info=None):

    app = Flask(__name__)

    app_settings = os.getenv("APP_SETTINGS")
    app.config.from_object(app_settings)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from project.landing.routes import landing_blueprint

    app.register_blueprint(landing_blueprint)

    from project.dashboard.routes import dashboard_blueprint

    app.register_blueprint(dashboard_blueprint)

    from project.errors.routes import errors_blueprint

    app.register_blueprint(errors_blueprint)

    @app.shell_context_processor
    def ctx():
        return {"app": app, "db": db}

    return app

project/dashboard/routes.py
from flask import Blueprint, flash, jsonify, redirect, render_template, url_for
from flask_login import current_user, login_required

from project import db
from project.forms import ProductForm
from project.models import Product

dashboard_blueprint = Blueprint("dashboard", __name__)


@dashboard_blueprint.route("/dashboard", methods=["GET", "POST"])
@login_required
def index():
    product_count = db.session.query(Product).filter_by(owner=current_user).count()
    db.session.close()
    form = ProductForm()
    if form.validate_on_submit():
        if product_count >= 5:
            flash(
                """Free accounts only get 5 saved searches,
                  upgrade your account!""",
                "warning",
            )
            return redirect(url_for("dashboard.index"))

        product = Product(title=form.title.data, url=form.url.data, owner=current_user)
        db.session.add(product)
        db.session.commit()
        db.session.close()
        flash("Your search is now saved!", "success")
        return redirect(url_for("dashboard.index"))

    products = db.session.query(Product).filter_by(owner=current_user)
    return render_template(
        "dashboard/index.html",
        title="Dashboard",
        form=form,
        products=products,
        count=product_count,
    )


@dashboard_blueprint.route("/delete/<product_id>", methods=["POST"])
def delete(product_id):
    product = Product.query.filter_by(id=product_id, owner=current_user).first()
    if product is None:
        flash("That search is not in the database!", "warning")
        return redirect(url_for("dashboard.index"))
    db.session.delete(product)
    db.session.commit()
    db.session.close()
    flash("Your search has been removed!", "success")
    return redirect(url_for("dashboard.index"))


@dashboard_blueprint.route("/async_delete/<product_id>", methods=["POST"])
def async_delete(product_id):
    product = Product.query.filter_by(id=product_id, owner=current_user).first()
    db.session.delete(product)
    db.session.commit()
    db.session.close()
    return jsonify(status="success")

project/landing/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user
from werkzeug.urls import url_parse

from project import db
from project.forms import LoginForm, RegistrationForm
from project.models import User

landing_blueprint = Blueprint("landing", __name__)


@landing_blueprint.route("/", methods=["GET", "POST"])
def index():
    return render_template("landing/index.html", title="Home")


@landing_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        db.session.close()
        flash("Congratulations, you are now a registered user!", "success")

        login_user(user)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("dashboard.index")
        return redirect(next_page)
    return render_template("landing/register.html", title="Register", form=form)


@landing_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("landing.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password", "danger")
            return redirect(url_for("landing.login"))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("dashboard.index")
        return redirect(next_page)
    return render_template("landing/login.html", title="Sign In", form=form)


@landing_blueprint.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("landing.index"))

project/routes.py
# from flask import render_template, flash, redirect, request, url_for, jsonify
# from project import app, db
# from flask_login import current_user, login_user, logout_user, login_required
# from project.models import User, Product
# from project.forms import LoginForm, RegistrationForm, ProductForm
# from werkzeug.urls import url_parse
#
# # Public Routes
# @app.route("/", methods=["GET", "POST"])
# def index():
#     return render_template("landing.html", title="Home")
#
#
# # Auth Routes
# @app.route("/register", methods=["GET", "POST"])
# def register():
#     if current_user.is_authenticated:
#         return redirect(url_for("dashboard"))
#     form = RegistrationForm()
#     if form.validate_on_submit():
#         user = User(username=form.username.data, email=form.email.data)
#         user.set_password(form.password.data)
#         db.session.add(user)
#         db.session.commit()
#         db.session.close()
#         flash("Congratulations, you are now a registered user!", "success")
#
#         login_user(user)
#         next_page = request.args.get("next")
#         if not next_page or url_parse(next_page).netloc != "":
#             next_page = url_for("dashboard")
#         return redirect(next_page)
#     return render_template("register.html", title="Register", form=form)
#
#
# @app.route("/login", methods=["GET", "POST"])
# def login():
#     if current_user.is_authenticated:
#         return redirect(url_for("index"))
#     form = LoginForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(username=form.username.data).first()
#         if user is None or not user.check_password(form.password.data):
#             flash("Invalid username or password", "danger")
#             return redirect(url_for("login"))
#         login_user(user, remember=form.remember_me.data)
#         next_page = request.args.get("next")
#         if not next_page or url_parse(next_page).netloc != "":
#             next_page = url_for("dashboard")
#         return redirect(next_page)
#     return render_template("login.html", title="Sign In", form=form)
#
#
# @app.route("/logout")
# def logout():
#     logout_user()
#     return redirect(url_for("index"))
#
#
# # Search Dashboard Routes
# @app.route("/dashboard", methods=["GET", "POST"])
# @login_required
# def dashboard():
#     product_count = db.session.query(Product).filter_by(owner=current_user).count()
#     db.session.close()
#     form = ProductForm()
#     if form.validate_on_submit():
#         if product_count >= 5:
#             flash(
#                 """Free accounts only get 5 saved searches,
#                   upgrade your account!""",
#                 "warning",
#             )
#             return redirect(url_for("dashboard"))
#
#         product = Product(title=form.title.data, url=form.url.data, owner=current_user)
#         db.session.add(product)
#         db.session.commit()
#         db.session.close()
#         flash("Your search is now saved!", "success")
#         return redirect(url_for("dashboard"))
#
#     products = db.session.query(Product).filter_by(owner=current_user)
#     return render_template(
#         "dashboard.html",
#         title="Dashboard",
#         form=form,
#         products=products,
#         count=product_count,
#     )
#
#
# @app.route("/delete/<product_id>", methods=["POST"])
# def delete(product_id):
#     product = Product.query.filter_by(id=product_id, owner=current_user).first()
#     if product is None:
#         flash("That search is not in the database!", "warning")
#         return redirect(url_for("dashboard"))
#     db.session.delete(product)
#     db.session.commit()
#     db.session.close()
#     flash("Your search has been removed!", "success")
#     return redirect(url_for("dashboard"))
#
#
# @app.route("/async_delete/<product_id>", methods=["POST"])
# def async_delete(product_id):
#     product = Product.query.filter_by(id=product_id, owner=current_user).first()
#     db.session.delete(product)
#     db.session.commit()
#     db.session.close()
#     return jsonify(status="success")

project/templates/landing/index.html
{% extends "layout.html" %}

{% block content %}

<!-- Hero Section -->
<section class="text-center">

  <div class="row align-items-center">
    <div class="col">
      <h1 class="large-heading">Daily Poshmark Reminders</h1>
      <br>
      <p class="sub-heading">
        Quit bookmarking pages and get daily notifications of newly posted items.
      </p>
    </div>
    <div class="col">
      <img src="{{ url_for('static', filename='posh-shot.jpg') }}" style="height: 400px" alt="Email Mockup">
    </div>
  </div>
</section>

<!-- Pricing Section -->
<section id="pricing">
  <div class="row">
    <div class="col">
      <div class="price-box text-center shadow">
        <h2 class="small-heading">Free Forever</h2>
        <h1>$0 </h1>
        <br>
        <p>5 saved searches</p>
        <p>Daily email updates</p>
        <br>
        <a href="{{ url_for('landing.register') }}" class="btn btn-primary my-2">Join now</a>
      </div>
    </div>
    <div class="col">
      <div class="price-box text-center shadow-sm">
        <h2 class="small-heading">Premium</h2>
        <h1>$5</h1>
        <br>
        <p>Unlimted saved searches</p>
        <p>Daily email updates</p>
        <br>
        <button type="button" class="btn btn-lg btn-primary" disabled>Pay now</button>
      </div>
    </div>
  </div>
</section>

{% endblock %}

project/templates/landing/login.html
{% extends "layout.html" %}

{% block content %}
<section>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-body">
          <h1>Sign In</h1>
          <!-- novalidate turns of web form validation, to test server side validation -->
          <form action="" method="post" novalidate>
              {{ form.hidden_tag() }}
              <div class="form-group">
                {{ form.username.label }}<br>
                {{ form.username(size=32, class='form-control') }}<br>
                {% for error in form.username.errors %}
                  <div class="alert alert-danger" role="alert">{{error}}</div>
                {% endfor %}
              </div>
              <div class="form-group">
                {{ form.password.label }}<br>
                {{ form.password(size=32, class='form-control') }}<br>
                {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">{{error}}</div>
                {% endfor %}
              </div>
              <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
              <p>{{ form.submit(class='btn btn-primary') }}</p>
          </form>
          <p>New User? <a href="{{ url_for('landing.register') }}">Click to Register!</a></p>
        </div>
      </div>
    </div>
  </div>

</section>
{% endblock %}

project/templates/landing/register.html
{% extends "layout.html" %}

{% block content %}
<section>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-body">
          <h1>Register</h1>
          <form action="" method="post">
              {{ form.hidden_tag() }}
              <div class="form-group">
                  {{ form.username.label }}<br>
                  {{ form.username(size=32, class='form-control') }}<br>
                  {% for error in form.username.errors %}
                  <div class="alert alert-danger" role="alert">{{error}}</div>
                  {% endfor %}
              </div>
              <div class="form-group">
                  {{ form.email.label }}<br>
                  {{ form.email(size=64, class='form-control') }}<br>
                  {% for error in form.email.errors %}
                  <div class="alert alert-danger" role="alert">{{error}}</div>
                  {% endfor %}
              </div>
              <div class="form-group">
                  {{ form.password.label }}<br>
                  {{ form.password(size=32, class='form-control') }}<br>
                  {% for error in form.password.errors %}
                  <div class="alert alert-danger" role="alert">{{error}}</div>
                  {% endfor %}
              </div>
              <div class="form-group">
                  {{ form.password2.label }}<br>
                  {{ form.password2(size=32, class='form-control') }}<br>
                  {% for error in form.password2.errors %}
                  <div class="alert alert-danger" role="alert">{{error}}</div>
                  {% endfor %}
              </div>
              <p>{{ form.submit(class='btn btn-primary') }}</p
              <p>Already Registered? <a href="{{ url_for('landing.login') }}">Click to Login!</a></p>
          </form>
        </div>
      </div>
    </div>
  </div>

</section>
{% endblock %}